// tailwind.config.js
export default {
  content: ['./src/**/*.tsx'], // ajusta a tu proyecto
  theme: {
    extend: {
      backgroundColor: {
        'neutral-primary': 'var(--background-neutral-primary)',
        'neutral-secondary': 'var(--background-neutral-secondary)',
        'neutral-tertiary': 'var(--background-neutral-tertiary)',
        'neutral-inverse-primary': 'var(--background-neutral-inverse-primary)',
        'neutral-inverse-secondary': 'var(--background-neutral-inverse-secondary)',
        'neutral-inverse-tertiary': 'var(--background-neutral-inverse-tertiary)',
        'brand-primary': 'var(--background-brand-primary)',
        'brand-secondary': 'var(--background-brand-secondary)',
        'brand-tertiary': 'var(--background-brand-tertiary)',
        'neutral-disabled': 'var(--background-neutral-disabled)',

        'success-subtle': 'var(--background-semantic-success-subtle)',
        'success-bold': 'var(--background-semantic-success-bold)',
        'warning-subtle': 'var(--background-semantic-warning-subtle)',
        'warning-bold': 'var(--background-semantic-warning-bold)',
        'error-subtle': 'var(--background-semantic-error-subtle)',
        'error-bold': 'var(--background-semantic-error-bold)',
        'info-subtle': 'var(--background-semantic-info-subtle)',
        'info-bold': 'var(--background-semantic-info-bold)',

        'area-pink': 'var(--backgroundareas-pink)',
        'area-red': 'var(--backgroundareas-red)',
        'area-yellow': 'var(--backgroundareas-yellow)',
        'area-orange': 'var(--backgroundareas-orange)',
        'area-purple': 'var(--backgroundareas-purple)',
        'area-green': 'var(--backgroundareas-green)',
        'area-blue': 'var(--backgroundareas-blue)',
        'area-gray': 'var(--backgroundareas-gray)',
      },
      textColor: {
        'neutral-primary': 'var(--text-neutral-primary)',
        'neutral-secondary': 'var(--text-neutral-secondary)',
        'neutral-tertiary': 'var(--text-neutral-tertiary)',
        'neutral-disabled': 'var(--text-neutral-disabled)',
        'neutral-inverse-primary': 'var(--text-neutral-inverse-primary)',
        'neutral-inverse-secondary': 'var(--text-neutral-inverse-secondary)',
        'neutral-inverse-tertiary': 'var(--text-neutral-inverse-tertiary)',
        'brand-primary': 'var(--text-brand-primary)',
        'brand-inverse': 'var(--text-brand-inverse)',
        'success-primary': 'var(--text-semantic-success-primary)',
        'success-inverse': 'var(--text-semantic-success-inverse)',
        'warning-primary': 'var(--text-semantic-warning-primary)',
        'warning-inverse': 'var(--text-semantic-warning-inverse)',
        'error-primary': 'var(--text-semantic-error-primary)',
        'error-inverse': 'var(--text-semantic-error-inverse)',
        'info-primary': 'var(--text-semantic-info-primary)',
        'info-inverse': 'var(--text-semantic-info-inverse)',
      },
      borderColor: {
        'neutral-primary': 'var(--border-neutral-primary)',
        'neutral-secondary': 'var(--border-neutral-secondary)',
        'neutral-inverse-primary': 'var(--border-neutral-inverse-primary)',
        'neutral-inverse-secondary': 'var(--border-neutral-inverse-secondary)',
        'brand-primary': 'var(--border-brand-primary)',
        'brand-inverse': 'var(--border-brand-inverse)',
        'success-primary': 'var(--border-semantic-success-primary)',
        'success-inverse': 'var(--border-semantic-success-inverse)',
        'warning-primary': 'var(--border-semantic-warning-primary)',
        'warning-inverse': 'var(--border-semantic-warning-inverse)',
        'error-primary': 'var(--border-semantic-error-primary)',
        'error-inverse': 'var(--border-semantic-error-inverse)',
        'info-primary': 'var(--border-semantic-info-primary)',
        'info-inverse': 'var(--border-semantic-info-inverse)',
        'icons': 'var(--border-icons)',
      },
    },
  },
  plugins: [],
};
